<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'category_id' => 2,
                'name' => 'Bayam Segar',
                'slug' => 'bayam-segar',
                'short_description' => 'Sayur hijau kaya zat besi',
                'description' => 'Bayam segar cocok untuk dibuat sayur bening atau tumis.',
                'price' => 8000,
                'original_price' => 9000,
                'discount_percent' => 10,
                'availability' => 'available',
                'stock' => 50,
                'unit' => 'ikat',
                'images' => [
                    ['products/bayam.png', 1],
                    ['products/bayam2.png', 0],
                ],
            ],
            [
                'category_id' => 3,
                'name' => 'Apel Fuji',
                'slug' => 'apel-fuji',
                'short_description' => 'Buah apel segar dari Fuji',
                'description' => 'Apel Fuji manis dan renyah, cocok untuk camilan sehat.',
                'price' => 15000,
                'original_price' => 17000,
                'discount_percent' => 12,
                'availability' => 'available',
                'stock' => 40,
                'unit' => 'kg',
                'images' => [
                    ['products/apel.png', 1],
                    ['products/apel2.png', 0],
                ],
            ],
            [
                'category_id' => 4,
                'name' => 'Ayam Utuh',
                'slug' => 'ayam-utuh',
                'short_description' => 'Ayam utuh segar',
                'description' => 'Ayam utuh segar cocok untuk berbagai masakan.',
                'price' => 35000,
                'original_price' => 38000,
                'discount_percent' => 8,
                'availability' => 'available',
                'stock' => 30,
                'unit' => 'kg',
                'images' => [
                    ['products/ayam.png', 1],
                ],
            ],
            [
                'category_id' => 5,
                'name' => 'Beras Premium',
                'slug' => 'beras-premium',
                'short_description' => 'Beras pulen kualitas premium',
                'description' => 'Beras premium cocok untuk nasi harian keluarga.',
                'price' => 12000,
                'original_price' => 13000,
                'discount_percent' => 7,
                'availability' => 'available',
                'stock' => 100,
                'unit' => 'kg',
                'images' => [
                    ['products/beras.png', 1],
                ],
            ],
            [
                'category_id' => 6,
                'name' => 'Bawang Merah',
                'slug' => 'bawang-merah',
                'short_description' => 'Bawang merah segar',
                'description' => 'Bawang merah untuk bumbu masakan sehari-hari.',
                'price' => 18000,
                'original_price' => 20000,
                'discount_percent' => 10,
                'availability' => 'available',
                'stock' => 60,
                'unit' => 'kg',
                'images' => [
                    ['products/bawang-merah.png', 1],
                ],
            ],
            [
                'category_id' => 3,
                'name' => 'Pisang Cavendish',
                'slug' => 'pisang-cavendish',
                'short_description' => 'Pisang manis dan lembut',
                'description' => 'Pisang Cavendish cocok untuk sarapan atau camilan.',
                'price' => 20000,
                'original_price' => 22000,
                'discount_percent' => 9,
                'availability' => 'available',
                'stock' => 35,
                'unit' => 'kg',
                'images' => [
                    ['products/pisang.png', 1],
                ],
            ],
            [
                'category_id' => 2,
                'name' => 'Wortel Organik',
                'slug' => 'wortel-organik',
                'short_description' => 'Wortel segar dan manis',
                'description' => 'Wortel organik cocok untuk sup dan salad.',
                'price' => 9000,
                'original_price' => 10000,
                'discount_percent' => 10,
                'availability' => 'available',
                'stock' => 45,
                'unit' => 'kg',
                'images' => [
                    ['products/wortel.png', 1],
                ],
            ],
            [
                'category_id' => 7,
                'name' => 'Susu UHT Full Cream',
                'slug' => 'susu-uht-full-cream',
                'short_description' => 'Susu UHT segar',
                'description' => 'Susu UHT full cream untuk nutrisi harian.',
                'price' => 14000,
                'original_price' => 15000,
                'discount_percent' => 7,
                'availability' => 'available',
                'stock' => 80,
                'unit' => 'liter',
                'images' => [
                    ['products/susu.png', 1],
                ],
            ],
            [
                'category_id' => 10,
                'name' => 'Keripik Kentang',
                'slug' => 'keripik-kentang',
                'short_description' => 'Keripik kentang renyah',
                'description' => 'Keripik kentang cocok untuk camilan keluarga.',
                'price' => 12000,
                'original_price' => 13000,
                'discount_percent' => 8,
                'availability' => 'available',
                'stock' => 70,
                'unit' => 'pack',
                'images' => [
                    ['products/keripik-kentang.png', 1],
                ],
            ],
            [
                'category_id' => 11,
                'name' => 'Jus Nanas',
                'slug' => 'jus-nanas',
                'short_description' => 'Jus nanas segar',
                'description' => 'Jus nanas segar tanpa pengawet.',
                'price' => 10000,
                'original_price' => 11000,
                'discount_percent' => 9,
                'availability' => 'available',
                'stock' => 50,
                'unit' => 'botol',
                'images' => [
                    ['products/jus-nanas.png', 1],
                ],
            ],
            [
                'category_id' => 12,
                'name' => 'Burger King',
                'slug' => 'burger-king',
                'short_description' => 'makanan cepat saji',
                'description' => 'Burger King makanan cepat saji favorit keluarga.',
                'price' => 27000,
                'original_price' => 30000,
                'discount_percent' => 10,
                'availability' => 'available',
                'stock' => 20,
                'unit' => 'pcs',
                'images' => [
                    ['products/burger-king.png', 1],
                ],
            ],
            [
                'category_id' => 12,
                'name' => 'Pizza Hut',
                'slug' => 'pizza-hut',
                'short_description' => 'Pizza siap saji',
                'description' => 'Pizza Hut dengan topping melimpah.',
                'price' => 50000,
                'original_price' => 55000,
                'discount_percent' => 9,
                'availability' => 'available',
                'stock' => 15,
                'unit' => 'pcs',
                'images' => [
                    ['products/pizza-hut.png', 1],
                ],
            ],
            [
                'category_id' => 2,
                'name' => 'Kangkung Segar',
                'slug' => 'kangkung-segar',
                'short_description' => 'Sayur kangkung segar',
                'description' => 'Kangkung segar cocok untuk tumis.',
                'price' => 7000,
                'original_price' => 8000,
                'discount_percent' => 12,
                'availability' => 'available',
                'stock' => 55,
                'unit' => 'ikat',
                'images' => [
                    ['products/kangkung.png', 1],
                ],
            ],
            [
                'category_id' => 3,
                'name' => 'Mangga Harum Manis',
                'slug' => 'mangga-harum-manis',
                'short_description' => 'Mangga harum dan manis',
                'description' => 'Mangga harum manis cocok untuk jus dan rujak.',
                'price' => 18000,
                'original_price' => 20000,
                'discount_percent' => 10,
                'availability' => 'available',
                'stock' => 30,
                'unit' => 'kg',
                'images' => [
                    ['products/mangga.png', 1],
                ],
            ],
            [
                'category_id' => 4,
                'name' => 'Daging Sapi',
                'slug' => 'daging-sapi',
                'short_description' => 'Daging sapi segar',
                'description' => 'Daging sapi segar untuk rendang dan steak.',
                'price' => 90000,
                'original_price' => 95000,
                'discount_percent' => 5,
                'availability' => 'available',
                'stock' => 25,
                'unit' => 'kg',
                'images' => [
                    ['products/daging-sapi.png', 1],
                ],
            ],
            [
                'category_id' => 5,
                'name' => 'Minyak Goreng',
                'slug' => 'minyak-goreng',
                'short_description' => 'Minyak goreng kemasan',
                'description' => 'Minyak goreng untuk kebutuhan dapur.',
                'price' => 14000,
                'original_price' => 15000,
                'discount_percent' => 7,
                'availability' => 'available',
                'stock' => 60,
                'unit' => 'liter',
                'images' => [
                    ['products/minyak-goreng.png', 1],
                ],
            ],
            [
                'category_id' => 6,
                'name' => 'Cabe Merah',
                'slug' => 'cabe-merah',
                'short_description' => 'Cabe merah segar',
                'description' => 'Cabe merah untuk sambal dan masakan pedas.',
                'price' => 25000,
                'original_price' => 27000,
                'discount_percent' => 7,
                'availability' => 'available',
                'stock' => 40,
                'unit' => 'kg',
                'images' => [
                    ['products/cabe-merah.png', 1],
                ],
            ],
            [
                'category_id' => 7,
                'name' => 'Keju Cheddar',
                'slug' => 'keju-cheddar',
                'short_description' => 'Keju cheddar olahan',
                'description' => 'Keju cheddar cocok untuk roti dan pizza.',
                'price' => 30000,
                'original_price' => 32000,
                'discount_percent' => 6,
                'availability' => 'available',
                'stock' => 30,
                'unit' => 'pack',
                'images' => [
                    ['products/keju.png', 1],
                ],
            ],
            [
                'category_id' => 10,
                'name' => 'Kacang Almond',
                'slug' => 'kacang-almond',
                'short_description' => 'Kacang almond panggang',
                'description' => 'Kacang almond panggang sehat untuk camilan.',
                'price' => 35000,
                'original_price' => 37000,
                'discount_percent' => 5,
                'availability' => 'available',
                'stock' => 25,
                'unit' => 'pack',
                'images' => [
                    ['products/almond.png', 1],
                ],
            ],
            [
                'category_id' => 11,
                'name' => 'Teh Botol',
                'slug' => 'teh-botol',
                'short_description' => 'Teh botol segar',
                'description' => 'Teh botol segar untuk pelepas dahaga.',
                'price' => 6000,
                'original_price' => 7000,
                'discount_percent' => 14,
                'availability' => 'available',
                'stock' => 100,
                'unit' => 'botol',
                'images' => [
                    ['products/teh-botol.png', 1],
                ],
            ],
        ];

        foreach ($products as $data) {
            $product = Product::create([
                'category_id' => $data['category_id'],
                'name' => $data['name'],
                'slug' => $data['slug'],
                'short_description' => $data['short_description'],
                'description' => $data['description'],
                'price' => $data['price'],
                'original_price' => $data['original_price'],
                'discount_percent' => $data['discount_percent'],
                'availability' => $data['availability'],
                'stock' => $data['stock'],
                'unit' => $data['unit'],
            ]);

            foreach ($data['images'] as $img) {
                ProductImage::create([
                    'product_id' => $product->id,
                    'image_url' => $img[0],
                    'is_primary' => $img[1],
                ]);
            }
        }
    }
}